---
- name: Provision oracle ebs instance
  ec2:
    key_name: "{{ key_name }}" 
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_id }}"
    wait: yes
    wait_timeout: 500
    volumes:
     - device_name: "{{ volume_device_name }}"
       volume_type: "{{ volume_type }}"
       volume_size: "{{ volume_size }}"
       delete_on_termination: True
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: no
    count: 1
    instance_tags:
     Name: "{{ instance_name|lower }}"
    region: "{{ aws_region }}"
  register: ec2

- debug: var=ec2

- name: Write the instance id to a file
  shell: echo "{{ ec2.instance_ids }}" | tr -d "[]u'" > ./instance_ids.txt

- name: save IP to inventory file
  copy: content={{ ec2["instances"][0]["private_ip"] }} dest=./hosts

- name: Wait for SSH to come up
  wait_for: host={{ ec2["instances"][0]["private_ip"] }} port=22 delay=60 timeout=320 state=started

- name: Add IP to ec2_hosts group
  add_host: hostname={{ ec2["instances"][0]["private_ip"] }} groups=ec2_hosts
