---
- name: Create AWS Oracle EBS EC2
  hosts: 127.0.0.1
  connection: local
  remote_user: "{{ ansible_user }}"
  roles:
    - aws_create # Call roles/create, register the instance private_ip
    - { role: aws_route53, ip_address: '{{ ec2["instances"][0]["private_ip"] }}' } # Call roles/route53

- name: Configure Oracle EBS Instance
  hosts: ec2_hosts # Generated group from Create AWS Instance
  remote_user: "{{ ansible_user }}"

  pre_tasks:
    - include_vars: secrets.yml

  roles:
    - common
